blank_issues_enabled: false
contact_links:
  - name: Get Help
    url: https://github.com/gustavomorinaga/github-unfollow-checker/discussions/new?category=help
    about: If you can't get something to work the way you expect, open a question in our discussion forums.
